<?php 

$livros = [
    ['id' => 1, 'titulo' => 'O Senhor dos Anéis: A Sociedade do Anel 1', 'autor' => 'J. R. R. Tolkien', 'descricao' => 'A Sociedade do Anel é a primeira parte da trilogia O Senhor dos Anéis, de J.R.R. Tolkien. Nela, Frodo Bolseiro e oito companheiros partem em uma jornada para destruir o Um Anel e salvar a Terra-média.'],
    ['id' => 2, 'titulo' => 'O Senhor dos Anéis: A Sociedade do Anel 2', 'autor' => 'J. R. R. Tolkien', 'descricao' => 'A Sociedade do Anel é a primeira parte da trilogia O Senhor dos Anéis, de J.R.R. Tolkien. Nela, Frodo Bolseiro e oito companheiros partem em uma jornada para destruir o Um Anel e salvar a Terra-média.'],
    ['id' => 6, 'titulo' => 'O Senhor dos Anéis: A Sociedade do Anel 3', 'autor' => 'J. R. R. Tolkien', 'descricao' => 'A Sociedade do Anel é a primeira parte da trilogia O Senhor dos Anéis, de J.R.R. Tolkien. Nela, Frodo Bolseiro e oito companheiros partem em uma jornada para destruir o Um Anel e salvar a Terra-média.'],
    ['id' => 4, 'titulo' => 'O Senhor dos Anéis: A Sociedade do Anel 4', 'autor' => 'J. R. R. Tolkien', 'descricao' => 'A Sociedade do Anel é a primeira parte da trilogia O Senhor dos Anéis, de J.R.R. Tolkien. Nela, Frodo Bolseiro e oito companheiros partem em uma jornada para destruir o Um Anel e salvar a Terra-média.'],
    ['id' => 5, 'titulo' => 'O Senhor dos Anéis: A Sociedade do Anel 5', 'autor' => 'J. R. R. Tolkien', 'descricao' => 'A Sociedade do Anel é a primeira parte da trilogia O Senhor dos Anéis, de J.R.R. Tolkien. Nela, Frodo Bolseiro e oito companheiros partem em uma jornada para destruir o Um Anel e salvar a Terra-média.'],
    ['id' => 6, 'titulo' => 'O Senhor dos Anéis: A Sociedade do Anel 6', 'autor' => 'J. R. R. Tolkien', 'descricao' => 'A Sociedade do Anel é a primeira parte da trilogia O Senhor dos Anéis, de J.R.R. Tolkien. Nela, Frodo Bolseiro e oito companheiros partem em uma jornada para destruir o Um Anel e salvar a Terra-média.'],
    ['id' => 7, 'titulo' => 'O Senhor dos Anéis: A Sociedade do Anel 7', 'autor' => 'J. R. R. Tolkien', 'descricao' => 'A Sociedade do Anel é a primeira parte da trilogia O Senhor dos Anéis, de J.R.R. Tolkien. Nela, Frodo Bolseiro e oito companheiros partem em uma jornada para destruir o Um Anel e salvar a Terra-média.'],
    ['id' => 8, 'titulo' => 'O Senhor dos Anéis: A Sociedade do Anel 8', 'autor' => 'J. R. R. Tolkien', 'descricao' => 'A Sociedade do Anel é a primeira parte da trilogia O Senhor dos Anéis, de J.R.R. Tolkien. Nela, Frodo Bolseiro e oito companheiros partem em uma jornada para destruir o Um Anel e salvar a Terra-média.'],
    ['id' => 9, 'titulo' => 'O Senhor dos Anéis: A Sociedade do Anel 9', 'autor' => 'J. R. R. Tolkien', 'descricao' => 'A Sociedade do Anel é a primeira parte da trilogia O Senhor dos Anéis, de J.R.R. Tolkien. Nela, Frodo Bolseiro e oito companheiros partem em uma jornada para destruir o Um Anel e salvar a Terra-média.'],
];

$filmes = [
    ['id' => 1, 'titulo' => 'Shrek 3', 'diretor' => 'Chris Miller', 'sinopse' => 'Doente em estado terminal, o rei Harold chama Fiona e Shrek para uma conversa sobre a sucessão de seu reinado e o futuro do povo em Tão Tão Distante. Como o genro se recusa a assumir o trono e prefere continuar sua pacata vida no pântano, a única saída é encontrar o primo Artur. Na companhia do Burro e do Gato de Botas, Shrek se encarrega da missão e sai em busca do parente que pode ser seu substituto no trono. Mas, antes de cumprir a tarefa, enfrenta as armações do ambicioso Príncipe Encantado.'],
    ['id' => 2, 'titulo' => 'Shrek 3', 'diretor' => 'Chris Miller', 'sinopse' => 'Doente em estado terminal, o rei Harold chama Fiona e Shrek para uma conversa sobre a sucessão de seu reinado e o futuro do povo em Tão Tão Distante. Como o genro se recusa a assumir o trono e prefere continuar sua pacata vida no pântano, a única saída é encontrar o primo Artur. Na companhia do Burro e do Gato de Botas, Shrek se encarrega da missão e sai em busca do parente que pode ser seu substituto no trono. Mas, antes de cumprir a tarefa, enfrenta as armações do ambicioso Príncipe Encantado.'],
    ['id' => 3, 'titulo' => 'Shrek 3', 'diretor' => 'Chris Miller', 'sinopse' => 'Doente em estado terminal, o rei Harold chama Fiona e Shrek para uma conversa sobre a sucessão de seu reinado e o futuro do povo em Tão Tão Distante. Como o genro se recusa a assumir o trono e prefere continuar sua pacata vida no pântano, a única saída é encontrar o primo Artur. Na companhia do Burro e do Gato de Botas, Shrek se encarrega da missão e sai em busca do parente que pode ser seu substituto no trono. Mas, antes de cumprir a tarefa, enfrenta as armações do ambicioso Príncipe Encantado.'],
    ['id' => 4, 'titulo' => 'Shrek 3', 'diretor' => 'Chris Miller', 'sinopse' => 'Doente em estado terminal, o rei Harold chama Fiona e Shrek para uma conversa sobre a sucessão de seu reinado e o futuro do povo em Tão Tão Distante. Como o genro se recusa a assumir o trono e prefere continuar sua pacata vida no pântano, a única saída é encontrar o primo Artur. Na companhia do Burro e do Gato de Botas, Shrek se encarrega da missão e sai em busca do parente que pode ser seu substituto no trono. Mas, antes de cumprir a tarefa, enfrenta as armações do ambicioso Príncipe Encantado.'],
    ['id' => 5, 'titulo' => 'Shrek 3', 'diretor' => 'Chris Miller', 'sinopse' => 'Doente em estado terminal, o rei Harold chama Fiona e Shrek para uma conversa sobre a sucessão de seu reinado e o futuro do povo em Tão Tão Distante. Como o genro se recusa a assumir o trono e prefere continuar sua pacata vida no pântano, a única saída é encontrar o primo Artur. Na companhia do Burro e do Gato de Botas, Shrek se encarrega da missão e sai em busca do parente que pode ser seu substituto no trono. Mas, antes de cumprir a tarefa, enfrenta as armações do ambicioso Príncipe Encantado.'],
    ['id' => 6, 'titulo' => 'Shrek 3', 'diretor' => 'Chris Miller', 'sinopse' => 'Doente em estado terminal, o rei Harold chama Fiona e Shrek para uma conversa sobre a sucessão de seu reinado e o futuro do povo em Tão Tão Distante. Como o genro se recusa a assumir o trono e prefere continuar sua pacata vida no pântano, a única saída é encontrar o primo Artur. Na companhia do Burro e do Gato de Botas, Shrek se encarrega da missão e sai em busca do parente que pode ser seu substituto no trono. Mas, antes de cumprir a tarefa, enfrenta as armações do ambicioso Príncipe Encantado.'],
    ['id' => 7, 'titulo' => 'Shrek 3', 'diretor' => 'Chris Miller', 'sinopse' => 'Doente em estado terminal, o rei Harold chama Fiona e Shrek para uma conversa sobre a sucessão de seu reinado e o futuro do povo em Tão Tão Distante. Como o genro se recusa a assumir o trono e prefere continuar sua pacata vida no pântano, a única saída é encontrar o primo Artur. Na companhia do Burro e do Gato de Botas, Shrek se encarrega da missão e sai em busca do parente que pode ser seu substituto no trono. Mas, antes de cumprir a tarefa, enfrenta as armações do ambicioso Príncipe Encantado.'],
    ['id' => 8, 'titulo' => 'Shrek 3', 'diretor' => 'Chris Miller', 'sinopse' => 'Doente em estado terminal, o rei Harold chama Fiona e Shrek para uma conversa sobre a sucessão de seu reinado e o futuro do povo em Tão Tão Distante. Como o genro se recusa a assumir o trono e prefere continuar sua pacata vida no pântano, a única saída é encontrar o primo Artur. Na companhia do Burro e do Gato de Botas, Shrek se encarrega da missão e sai em busca do parente que pode ser seu substituto no trono. Mas, antes de cumprir a tarefa, enfrenta as armações do ambicioso Príncipe Encantado.'],
    ['id' => 9, 'titulo' => 'Shrek 3', 'diretor' => 'Chris Miller', 'sinopse' => 'Doente em estado terminal, o rei Harold chama Fiona e Shrek para uma conversa sobre a sucessão de seu reinado e o futuro do povo em Tão Tão Distante. Como o genro se recusa a assumir o trono e prefere continuar sua pacata vida no pântano, a única saída é encontrar o primo Artur. Na companhia do Burro e do Gato de Botas, Shrek se encarrega da missão e sai em busca do parente que pode ser seu substituto no trono. Mas, antes de cumprir a tarefa, enfrenta as armações do ambicioso Príncipe Encantado.'],
];

?>